title: "HCA Wrangler Docs"
site_url: https://ebi-ait.github.io/hca-ebi-wrangler-central/tree/ncbi_cloud/
remote_theme: pmarsceill/just-the-docs
# remote_theme: leakyabstractions/pretty-docs
search_enabled: true
aux_links:
  "Edit these Docs on GitHub":
    - "//github.com/ebi-ait/hca-ebi-wrangler-central/tree/ncbi_cloud/docs"
#   - "//github.com/ebi-ait/hca-ebi-wrangler-central/tree/master/docs"
